# Generated by Django 3.2.8 on 2021-10-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
    ]
